[package]
name = "ethereum_research"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = { version = "0.13.0", features = ["derive"] }
neptune = "13.0.0"
blstrs = "0.7.1"
typenum = "1.17.0"
